<a href="https://colab.research.google.com/github/nescoba/portafolio/blob/main/predicting_scores_mls_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline 
sns.set()

In [2]:
# pip install itscalledsoccer

In [3]:
from itscalledsoccer.client import AmericanSoccerAnalysis

asa_client = AmericanSoccerAnalysis() 

asa_client.get_teams(leagues='mls')

Gathering all players
Gathering all teams
Gathering all stadia
Gathering all managers
Gathering all referees
Finished initializing client


team_id               team_name team_short_name team_abbreviation  \
0   0KPqjA456v    San Jose Earthquakes        San Jose               SJE   
1   19vQ2095K6  New England Revolution     New England               NER   
2   4wM42l4qjB              Chivas USA          Chivas               CHV   
3   9z5k7Yg5A3      Philadelphia Union    Philadelphia               PHI   
4   a2lqR4JMr0          Real Salt Lake       Salt Lake               RSL   
5   a2lqRX2Mr0      New York Red Bulls        New York              NYRB   
6   APk5LGOMOW             CF Montréal        Montréal               MTL   
7   EKXMeX3Q64             D.C. United     D.C. United               DCU   
8   eVq3ya6MWO          Los Angeles FC  Los Angeles FC              LAFC   
9   gpMOLwl5zy               Austin FC          Austin               ATX   
10  jYQJ19EqGR     Seattle Sounders FC         Seattle               SEA   
11  jYQJ8EW5GR         Orlando City SC    Orlando City               ORL   
12  kaDQ0wRqEv               LA Galaxy       LA Galaxy               LAG   
13  KAqBN0Vqbg       Atlanta United FC         Atlanta               ATL   
14  kRQabn8MKZ              Toronto FC         Toronto               TOR   
15  kRQand1MKZ     Minnesota United FC       Minnesota               MIN   
16  lgpMOvnQzy  Vancouver Whitecaps FC       Vancouver               VAN   
17  mKAqBBmqbg               FC Dallas          Dallas               FCD   
18  mvzqoLZQap           Columbus Crew        Columbus               CLB   
19  NPqxKXZ59d            Charlotte FC       Charlotte               CLT   
20  NWMWlBK5lz           FC Cincinnati      Cincinnati               CIN   
21  pzeQZ6xQKw         Colorado Rapids        Colorado               COL   
22  Vj58weDM8n        New York City FC   New York City               NYC   
23  vzqoOgNqap            Nashville SC       Nashville               NSH   
24  WBLMvYAQxe     Portland Timbers FC        Portland               POR   
25  X0Oq66zq6D         Chicago Fire FC         Chicago               CHI   
26  YgOMngl5wN       Houston Dynamo FC         Houston               HOU   
27  Z2vQ1xlqrA    Sporting Kansas City     Kansas City               SKC   
28  zeQZkL1MKw          Inter Miami CF           Miami               MIA   

   competition  
0          mls  
1          mls  
2          mls  
3          mls  
4          mls  
5          mls  
6          mls  
7          mls  
8          mls  
9          mls  
10         mls  
11         mls  
12         mls  
13         mls  
14         mls  
15         mls  
16         mls  
17         mls  
18         mls  
19         mls  
20         mls  
21         mls  
22         mls  
23         mls  
24         mls  
25         mls  
26         mls  
27         mls  
28         mls

In [5]:
import statsmodels.api as sm

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [30]:
all_games = asa_client.get_games(leagues='mls')
all_games

game_id            date_time_utc  home_score  away_score home_team_id  \
0    315VVxG959  2022-03-07 03:00:00 UTC           1           1   eVq3ya6MWO   
1    9z5knLXjMA  2022-03-06 21:00:00 UTC           5           1   gpMOLwl5zy   
2    KAqBD3KBMb  2022-03-06 00:30:00 UTC           0           1   NPqxKXZ59d   
3    e7Mz8VGGqr  2022-03-05 23:00:00 UTC           1           1   kRQand1MKZ   
4    eVq3gvKVqW  2022-03-05 23:00:00 UTC           1           0   a2lqR4JMr0   
..          ...                      ...         ...         ...          ...   
429  xW5pyO8Jqg  2013-03-03 03:30:00 UTC           0           1   jYQJ19EqGR   
430  KPqjK3VYQ6  2013-03-03 01:30:00 UTC           1           0   mKAqBBmqbg   
431  kRQaolgj5K  2013-03-03 01:00:00 UTC           2           0   YgOMngl5wN   
432  9vQ2ZGnmQK  2013-03-02 23:30:00 UTC           1           0   lgpMOvnQzy   
433  NPqxxL8Xq9  2013-03-02 21:00:00 UTC           1           3   9z5k7Yg5A3   

    away_team_id  referee_id  stadium_id home_manager_id away_manager_id  \
0     WBLMvYAQxe  e7MzPKXqr0  7vQ7xbOMD1      NWMWxKe5lz      gpMOYv1qzy   
1     zeQZkL1MKw  jYQJnoVQGR  jYQJZDDQGR      0Oq6mNP56D      gpMOYJ7qzy   
2     kaDQ0wRqEv  9z5kJ7gMA3  KXMeOR2q64      gjMNG4k5Kp      Xj5Yx60Mbd   
3     vzqoOgNqap  gjMNk4v5Kp  odMXGRrQYL      OlMlYvy5Lz      gOMnDkAqwN   
4     jYQJ19EqGR  7VqG6KX5vW  e7MzlRjqr0      4wM4vOAqjB      odMXxreMYL   
..           ...         ...         ...             ...             ...   
429   APk5LGOMOW  zeQZl7D5Kw  9Yqda07QvJ      KXMeab1M64      315VKkEq9x   
430   pzeQZ6xQKw  vzqoWjkqap  eVq3alGMWO      a35rDN4QL6      gjMNk8v5Kp   
431   EKXMeX3Q64  EGMPPnAMaY  0x5g6ojM7O      4JMA4X9QKg      vzqoAjJMap   
432   kRQabn8MKZ  Oa5w9R9Q14  ljqEDnO5x0      ljqEWzAMx0      gjMNk0Y5Kp   
433   Z2vQ1xlqrA  a35r6KG5L6  NWMW8ZN5lz      KXMeAPkM64      N6MmpyLQEG   

     expanded_minutes  season_name  matchday  attendance  knockout_game  \
0                 100         2022         2       22102          False   
1                 100         2022         2       20738          False   
2                 100         2022         2       74479          False   
3                  96         2022         2           0          False   
4                  95         2022         2       20017          False   
..                ...          ...       ...         ...            ...   
429               101         2013         1       38998          False   
430               100         2013         1       18075          False   
431                95         2013         1       20019          False   
432                97         2013         1       21000          False   
433                97         2013         1       18160          False   

            last_updated_utc  extra_time  penalties  home_penalties  \
0    2022-03-07 05:30:09 UTC         NaN        NaN             NaN   
1    2022-03-06 23:38:24 UTC         NaN        NaN             NaN   
2    2022-03-07 03:55:19 UTC         NaN        NaN             NaN   
3    2022-03-07 01:57:19 UTC         NaN        NaN             NaN   
4    2022-03-06 03:22:17 UTC         NaN        NaN             NaN   
..                       ...         ...        ...             ...   
429                      NaN         NaN        NaN             NaN   
430                      NaN         NaN        NaN             NaN   
431                      NaN         NaN        NaN             NaN   
432                      NaN         NaN        NaN             NaN   
433                      NaN         NaN        NaN             NaN   

     away_penalties  
0               NaN  
1               NaN  
2               NaN  
3               NaN  
4               NaN  
..              ...  
429             NaN  
430             NaN  
431             NaN  
432             NaN  
433             NaN  

[3434 rows x 20 columns]

In [26]:
def construct_time_series_date(team_id, date):
    seasons = asa_client.get_game_xgoals(leagues='mls')
    seasons.loc[:, 'date_formated'] = pd.to_datetime(seasons['date_time_utc'])
    seasons = seasons[seasons['date_formated'] < date]

    seasons_team = seasons[(seasons['home_team_id']==team_id) | (seasons['away_team_id']==team_id)]
    team_home = seasons_team[seasons_team['home_team_id']==team_id]
    team_away = seasons_team[seasons_team['away_team_id']==team_id]

    team_home.loc[:,'teamxgoals'] = team_home['home_team_xgoals']
    team_away.loc[:,'teamxgoals'] = team_away['away_team_xgoals']

    team_home.loc[:,'teamgoals'] = team_home['home_goals']
    team_away.loc[:,'teamgoals'] = team_away['away_goals']

    team_home.loc[:,'oppoxgoals'] = team_home['away_team_xgoals']
    team_away.loc[:,'oppoxgoals'] = team_away['home_team_xgoals']

    team_home.loc[:,'oppogoals'] = team_home['away_goals']
    team_away.loc[:,'oppogoals'] = team_away['home_goals']

    team_home_red = team_home.loc[:, ['teamgoals', 'teamxgoals', 'oppoxgoals', 'oppogoals', 'date_formated']]
    team_away_red = team_away.loc[:, ['teamgoals', 'teamxgoals', 'oppoxgoals', 'oppogoals', 'date_formated']]

    team_red = pd.merge(team_home_red, team_away_red, how='outer')

    team_red = team_red.sort_values(by='date_formated')

    return team_red

In [60]:
def probs_game(home_id, away_id, date, arg):
    home_df = construct_time_series_date(home_id, pd.to_datetime(date))
    away_df = construct_time_series_date(away_id, pd.to_datetime(date))

    hteam_series = pd.Series(home_df['teamxgoals'].values, index=home_df['date_formated'])

    try:
        hmod = sm.tsa.ARIMA(hteam_series, order = (0,1,1))
        hres = hmod.fit()
        hlambda = hres.predict(start=(len(hteam_series)), end=(len(hteam_series)+0)).values
    except:
        try:
            hlambda = home_df.loc[len(home_df) -1 ,'teamxgoals']
        except:
            hlambda = 0.01


    ateam_series = pd.Series(away_df['teamxgoals'].values, index=away_df['date_formated'])
    
    try:
        amod = sm.tsa.ARIMA(ateam_series, order = (0,1,1))
        ares = amod.fit()
        alambda = ares.predict(start=(len(ateam_series)), end=(len(ateam_series)+0)).values
    except:
        try:
            alambda = away_df.loc[len(away_df) - 1, 'teamxgoals']
        except:
            alambda= 0.01


    n_simulations = 10000
    n_home = 0
    n_draw = 0
    n_away = 0

    for n in range(n_simulations):
        home_score = np.random.poisson(max(hlambda, 0.01))
        away_score = np.random.poisson(max(alambda, 0.01))
        if home_score > away_score:
            n_home += 1
        elif home_score < away_score:
            n_away += 1
        else:
            n_draw += 1 

    return (n_home / n_simulations, n_draw / n_simulations, n_away / n_simulations, arg)

In [61]:
probs_game('kRQand1MKZ', 'vzqoOgNqap', '2022-03-05 23:00:00 UTC', 'e7Mz8VGGqr')

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1667: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = value
/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/base/tsa_model.py:219: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/base/tsa_model.py:219: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/base/tsa_model.py:576: Value

(0.3972, 0.4633, 0.1395, 'e7Mz8VGGqr')

In [62]:
vprobs_game = np.vectorize(probs_game)
all_games.loc[:, 'date_formated'] = pd.to_datetime(all_games['date_time_utc'])
games = all_games[all_games['date_formated']>'2022-03-01 23:00:00 UTC']
vprobs_game(games['home_team_id'], games['away_team_id'], games['date_time_utc'], games['game_id'])

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1667: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = value
/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/base/tsa_model.py:219: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/base/tsa_model.py:219: ValueWarning: A date index has been provided, but it has no associated frequency information and so will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/base/tsa_model.py:576: Value

(array([0.0103, 0.009 , 0.6194, 0.3818, 0.3415, 0.2886, 0.6104, 0.0098,
        0.182 , 0.2826, 0.3586, 0.1613, 0.0082, 0.5175]),
 array([0.9803, 0.98  , 0.3766, 0.4719, 0.323 , 0.3289, 0.3852, 0.9803,
        0.809 , 0.7098, 0.4744, 0.4189, 0.9821, 0.4776]),
 array([0.0094, 0.011 , 0.004 , 0.1463, 0.3355, 0.3825, 0.0044, 0.0099,
        0.009 , 0.0076, 0.167 , 0.4198, 0.0097, 0.0049]),
 array(['315VVxG959', '9z5knLXjMA', 'KAqBD3KBMb', 'e7Mz8VGGqr',
        'eVq3gvKVqW', 'NWMWPw6E5l', 'Oa5w1RB4Q1', 'p6qbJ9mwq0',
        'XVqKBRm050', 'wvq9RAPwQW', 'jYQJ3oKkMG', 'Xj5YNBmRqb',
        'N6MmRwmx5E', 'ljqElgK45x'], dtype='<U10'))